name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x
          cache: npm

      - name: Install
        run: npm ci

      - run: npm run update -- --date 2022-06-02T08:23:05.896Z --apiKey ${{ secrets.API_KEY }} --serviceDomain ${{ secrets.SERVICE_DOMAIN }}

      - run: wget https://github.com/gohugoio/hugo/releases/download/v0.100.1/hugo_extended_0.100.1_Linux-64bit.tar.gz
      - run: tar -xf hugo_extended_0.100.1_Linux-64bit.tar.gz
      - run: ./hugo

      - name: Artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: public

      - name: Publish
        run: npx wrangler pages publish public --project-name=${{ secrets.PROJECT_NAME }} --commit-dirty=true
